### 프로퍼티 암호화
POST http://localhost:8888/encrypt
Content-Type: text/plain

beyond

### 프로퍼티 복호화
POST http://localhost:8888/decrypt
Content-Type: text/plain

ea5933fb0462c6addf60abb1e92c06d965f3f766e34dd2609cd5a1b8dd5cb133

### 프로퍼티 변경
POST http://localhost:8089/actuator/refresh
Content-Type: application/json